services:
  - type: web
    name: stress-research-platform-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/scripts/start.py
    envVars:
      - key: APP_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.7
